travis:
  secure:
    BINSTAR_TOKEN: J72nenlqu/9ljjSUj/qb0Pc9MKgt1R8f3OEGVwbe1NKNkQTCVOLGvBpw0vlylCKFoQthzOVz2bp6I7hC9EOpMnGDztNji1fKTlcKoQCKq52/gevB1UbPZe4GEhlhGbarIGLnppY43N21M+2TG74/m5o1v8VU1fLv6YP0ShIBligGQOxfK46f53ONH7ijtdTib3lAkJUgughKzf9Ri6xh3CS3VHL2POgHpgcR3whx9njpeB9NKG0D3/xv6gyLK55McmS2SXB0s/Gx1Rp1N49XYRmfhHY55eOyQfC40nfrCF7xlSaGulyOpHivKNIU0r+ZrwNi5Uy5AmiDntlys0pYDQSu8D3cB20lIhpqSR/WB+9PBkbyxdlDg7R8dss6oFpwLggvRHdCc2gbsgx5227WbehwgbEGLqntNxiRimQOkeayyX187WHoPuMRwgJJBITumDxKwAHWaMJeHhFW9vPe74cpvcLOMl/O6VUqg8xd2L7ZP4wOL7mC49FNjGwNUALe2A0uM4KoMT3VfxN7SCFxQUncvgxwnBc1S8GQgoCACrnqITrzsYtoI9xfPkC+ve04+S0YgTdEmyODZ895UsipeOePxf0Zxcn3qZpU3dIpJltnzCp6iGFhzxVBQAs80rH3ith9ynDL4MOEfjuDybKUgzdToCi+ubpgdFIGwIOstno=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
